sonarqube:
    image: sonarqube
    environment:
        SONARQUBE_JDBC_URL: jdbc:postgresql://172.17.0.1:5432/sonar
        VIRTUAL_HOST: sonarqube.opsadventures.com
        VIRTUAL_PORT: 9000
        CERT_NAME: default
    volumes:
        - /data/sonar/conf:/opt/sonarqube/conf
        - /data/sonar/data:/opt/sonarqube/data
        - /data/sonar/extensions:/opt/sonarqube/extensions
        - /data/sonar/plugins:/opt/sonarqube/lib/bundled-plugins

db:
    image: postgres
    environment:
        POSTGRES_USER: sonar
        POSTGRES_PASSWORD: sonar
    volumes:
        - /data/sonar-postgres:/var/lib/postgresql
        - /data/sonar-postgres/data:/var/lib/postgresql/data
    ports:
        - 172.17.0.1:5432:5432
